language: rust

sudo: required

rust:
  - beta
  - nightly

before_script:
  - rustup install nightly
  - rustup component add rustfmt-preview --toolchain nightly

script:
  - cargo +nightly fmt --verbose --all -- --check
  - cargo build --verbose --all

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
      cargo doc --all --no-deps --verbose &&
      echo "<meta http-equiv=refresh content=0;url=nes-wasm/index.html>" > target/doc/index.html &&
      git clone https://github.com/davisp/ghp-import.git &&
      ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/doc &&
      echo "Uploaded documentation"
    fi
